apiVersion: v1
kind: Service
metadata:
  namespace: tiflash-autoscale
  name: autoscale
  labels:
    app: autoscale
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: autoscale
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: tiflash-autoscale
  name: autoscale
spec:
  selector:
    matchLabels:
      app: autoscale # has to match .spec.template.metadata.labels
  serviceName: "autoscale"
  replicas: 1 # by default is 1
  minReadySeconds: 1 # by default is 0
  template:
    metadata:
      labels:
        app: autoscale # has to match .spec.selector.matchLabels
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: t3.xlarge # use instance type to split components(autoscaler,supervisor) between different nodes

      terminationGracePeriodSeconds: 1
      containers:
      - name: autoscale
        image: bestwoody/k8stest:1
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PD_ADDR
          value: "172.31.8.1:2379"
        - name: TIDB_STATUS_ADDR
          value: "172.31.7.1:4000"